name: flutter_credit_card_brazilian
description: Componente para Cartão de Credito.
version: 2.0.0
author: José Barreto <jbarretosantosjr@gmail.com>
homepage: https://github.com/JoseBarreto1/flutter_credit_card_brazilian
issue_tracker : https://github.com/JoseBarreto1/flutter_credit_card_brazilian/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - icons/
  fonts:
    - family: halter
      fonts:
        - asset: font/halter.ttf
